//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sm64wiikit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sm64wiikit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Add GC deadzone
        ///0304 000B345C 3BE00000
        ///0304 000B3478 7C7F1B78
        ///0304 000B3490 3BC00000
        ///0304 000B34AC 7C7E1B78
        ///0304 000B34C8 40800048
        ///
        ///# Add GC stick scaling
        ///0304 0005DC18 EC61E824
        ///0304 0005DC34 EC42E824
        ///0304 0005DC40 EC7E00F2
        ///0304 0005DC44 EC5E00B2
        ///
        ///# Unhook
        ///0304 0005DC4C FC60181E
        ///0304 0005DC54 FC40101E
        ///.
        /// </summary>
        public static string control_stick_mapping_off {
            get {
                return ResourceManager.GetString("control_stick_mapping_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Remove GC deadzone
        ///0304 000B345C 60000000
        ///0304 000B3478 60000000
        ///0304 000B3490 60000000
        ///0304 000B34AC 60000000
        ///0304 000B34C8 48000048
        ///
        ///# Remove GC stick scaling
        ///0304 0005DC18 FC600890
        ///0304 0005DC34 60000000
        ///0304 0005DC40 60000000
        ///0304 0005DC44 60000000
        ///
        ///# Hook
        ///0304 0005DC4C 4BFA289D
        ///0304 0005DC54 60000000
        ///
        ///# The
        ///0304 00000FF8 3FF00000
        ///0304 00000FFC 00000000
        ///0304 00001020 00000000
        ///0304 00001024 00000000
        ///0304 00001028 9421ff98
        ///0304 00001028 9421ff98
        ///0304 0000102c d8810060
        ///0304 00001 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string control_stick_mapping_on {
            get {
                return ResourceManager.GetString("control_stick_mapping_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 000B7FDC 4E800020
        ///0304 000C52CC 38000001
        ///0304 000C52D0 3863B9C0
        ///0304 000C52D4 9803000C.
        /// </summary>
        public static string crashes_fix_off {
            get {
                return ResourceManager.GetString("crashes_fix_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 000B7FDC 4800D2F0
        ///0304 000C52CC 3C808109
        ///0304 000C52D0 38A0007F
        ///0304 000C52D4 90A40D00.
        /// </summary>
        public static string crashes_fix_on {
            get {
                return ResourceManager.GetString("crashes_fix_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 00005AD4 41820008.
        /// </summary>
        public static string extended_ram_off {
            get {
                return ResourceManager.GetString("extended_ram_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 00005AD4 60000000.
        /// </summary>
        public static string extended_ram_on {
            get {
                return ResourceManager.GetString("extended_ram_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Add GC deadzone
        ///0304 000B345C 3BE00000
        ///0304 000B3478 7C7F1B78
        ///0304 000B3490 3BC00000
        ///0304 000B34AC 7C7E1B78
        ///0304 000B34C8 40800048
        ///
        ///# Add GC stick scaling
        ///0304 0005DC18 EC61E824
        ///0304 0005DC34 EC42E824
        ///0304 0005DC40 EC7E00F2
        ///0304 0005DC44 EC5E00B2
        ///
        ///# Hook
        ///0304 0005DC4C 4BFA289D
        ///0304 0005DC54 60000000
        ///
        ///# The
        ///0304 00000FF8 3FF00000
        ///0304 00000FFC 00000000
        ///0304 00001020 00000000
        ///0304 00001024 00000000
        ///0304 00001028 9421fff8
        ///0304 0000102c 90610000
        ///0304 00001030 90810004
        ///0304 00001034 3c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string framewalk_stick_mapping_off {
            get {
                return ResourceManager.GetString("framewalk_stick_mapping_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Remove GC deadzone
        ///0304 000B345C 60000000
        ///0304 000B3478 60000000
        ///0304 000B3490 60000000
        ///0304 000B34AC 60000000
        ///0304 000B34C8 48000048
        ///
        ///# Remove GC stick scaling
        ///0304 0005DC18 FC600890
        ///0304 0005DC34 60000000
        ///0304 0005DC40 60000000
        ///0304 0005DC44 60000000
        ///
        ///# Hook
        ///0304 0005DC4C 4BFA289D
        ///0304 0005DC54 60000000
        ///
        ///# The
        ///0304 00000FF8 3FF00000
        ///0304 00000FFC 00000000
        ///0304 00001020 00000000
        ///0304 00001024 00000000
        ///0304 00001028 3ff00000
        ///0304 0000102c 00000000
        ///0304 00001030 405a4000
        ///0304 00001 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string framewalk_stick_mapping_on {
            get {
                return ResourceManager.GetString("framewalk_stick_mapping_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] gzinject {
            get {
                object obj = ResourceManager.GetObject("gzinject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0302 0005C152 00007{0}0
        ///0302 0005C176 00000{0}0.
        /// </summary>
        public static string rom_size_tmpl {
            get {
                return ResourceManager.GetString("rom_size_tmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 0016B0B0 000000BE
        ///0304 0016B0B4 000000BE
        ///0304 0016B0B8 000000BE.
        /// </summary>
        public static string vc_shaded_picture_fix_off {
            get {
                return ResourceManager.GetString("vc_shaded_picture_fix_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0304 0016B0B0 000000FF
        ///0304 0016B0B4 000000FF
        ///0304 0016B0B8 000000FF.
        /// </summary>
        public static string vc_shaded_picture_fix_on {
            get {
                return ResourceManager.GetString("vc_shaded_picture_fix_on", resourceCulture);
            }
        }
    }
}
